### ISSUE TITLE
Issue with localization: Hangs in French Visual Studio

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [CoatiSoftware/vs-sourcetrail#56] opened 2019-06-24 13:59 UTC
On visual Studio 2019, brand new setup...
I installed the extension and tried to create a compilation database (extension/sourcetrails/create compilation database). Nothing happens (no UI is displayed).
Trying to do this again, the command is grayed out. I have to restart visual studio to see the option enabled again.

Switching the UI of Visual Studio from French to English, it now works as expected.

**Comment by Osse** [comment] 2019-07-04 13:19
I have a similar problem. The menu option does nothing, and afterwards it is greyed out.

I however haven't found a way to reenable it. Restarting does not help. Disabling other rather invasive plugins (Visual Assist) doesn't help either.

**Comment by mlangkabel** [comment] 2019-07-04 17:42
Can you try to enable logging for the Sourcetrail Extension (in your VS options -> Sourcetrail) and check what it says?

**Comment by Osse** [comment] 2019-07-04 18:12
I can provide exact logs in the morning, but I can say now that it doesn't contain anything relevant. It says "Initialization done" in the end, but with no errors preceeding it (except maybe the failure to connect to the sourcetrail application).

The first time it happened I *think* the logs said "Disabling UI" in a message but those logs have been lost.

**Comment by Osse** [comment] 2019-07-05 06:11
If Sourcetrail is running the log contains:
```
8:6:12	INFO	SourcetrailExtensionPackage.cs:363 (InitLogging)		Logging initialized for Sourcetrail Extension 2.0.2.128
8:6:13	INFO	SourcetrailExtensionPackage.cs:337 (InitNetwork)		Initializing Network with Server Port 6666 and Client Port 6667
8:6:13	INFO	SourcetrailExtensionPackage.cs:253 (InitializeAsync)		Initialization done
```

If it doesn't, the log contains:

```
8:9:4	INFO	SourcetrailExtensionPackage.cs:363 (InitLogging)		Logging initialized for Sourcetrail Extension 2.0.2.128
8:9:4	INFO	SourcetrailExtensionPackage.cs:337 (InitNetwork)		Initializing Network with Server Port 6666 and Client Port 6667
8:9:6	ERROR	NetworkUtility.cs:173 (Send)		Exception: No connection could be made because the target machine actively refused it 127.0.0.1:6667
8:9:6	INFO	SourcetrailExtensionPackage.cs:253 (InitializeAsync)		Initialization done
```

Just now the menu item was for a brief moment enabled. I quickly checked the logs, found nothing of interest, and when I got back to VS it was disabled again.

**Comment by mlangkabel** [comment] 2019-07-05 18:21
Hm, for me the logs look like this. When starting VS:
```
20:16:50	INFO	SourcetrailExtensionPackage.cs:363 (InitLogging)		Logging initialized for Sourcetrail Extension 2.0.2.128
20:16:50	INFO	SourcetrailExtensionPackage.cs:337 (InitNetwork)		Initializing Network with Server Port 6666 and Client Port 6667
20:16:52	ERROR	NetworkUtility.cs:173 (Send)		Exception: No connection could be made because the target machine actively refused it 127.0.0.1:6667
20:16:52	INFO	SourcetrailExtensionPackage.cs:253 (InitializeAsync)		Initialization done
```
After loading a solution:
```
20:16:55	INFO	SourcetrailExtensionPackage.cs:258 (OnSolutionOpened)		A solution was loaded, checking languages
20:16:55	INFO	SourcetrailExtensionPackage.cs:279 (OnSolutionOpened)		C/C++ project was detected.
20:16:55	INFO	SourcetrailExtensionPackage.cs:287 (OnSolutionOpened)		Enabling extension UI.
```
After closing VS (taken from the log file):
```
20:17:6	INFO	SourcetrailExtensionPackage.cs:313 (OnSolutionClosed)		Solution closed, disabling extension UI
```

So for you the whole "OnSolutionOpened" part is missing. Do you open a solution? Does it contain a C or C++ project?

**Comment by Osse** [comment] 2019-07-06 10:31
The solution in question contains several C++ projects. There is nothing that indicates that Visual Studio somehow thinks there are no C++ projects in the solution. Syntax highlighting, compiling and IntelliSense all work just fine.

I have made some discoveries: 

- If I create a Hello World solution in Visual Studio everything seems to work just fine.
- If I create a new solution using our in-house tool to create a solution that integrates wiith our infrastructure then it doesn't.
- The main difference is that our generated `vcxproj` files include two extra `*.props` files. If I remove those additions to the project file then I can create a database again.

The props file inclusion looks like this:

```diff
--- b/helloworld.vcxproj
+++ a/helloworld.vcxproj
@@ -30,6 +30,9 @@
   <ItemGroup>
     <ClCompile Include="main.cpp" />
   </ItemGroup>
+  <ImportGroup Label="PropertySheets">
+    <Import Project="$(ProjectName).pre.props" Condition="exists('$(ProjectName).pre.props')" Label="Preload Project Specific Properties" />
+  </ImportGroup>
   <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
   <PropertyGroup Condition="'$(Configuration)'=='Release'" Label="Configuration">
     <WholeProgramOptimization>true</WholeProgramOptimization>
@@ -53,7 +56,10 @@
   <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="PropertySheets">
     <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
   </ImportGroup>
+  <ImportGroup Label="PropertySheets">
+    <Import Project="$(ProjectName).props" Condition="exists('$(ProjectName).props')" Label="Project Specific Properties" />
+  </ImportGroup>
   <PropertyGroup Label="UserMacros" />
   <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
   <ImportGroup Label="ExtensionTargets" />
```

I will investigate further trying to narrow down what these files do that breaks the extension. But I am fairly sure they don't do anything extravagant. They add some standard include paths, compile flags and stuff like that.

**Comment by Osse** [comment] 2019-07-06 11:51
Gah, this is frustrating! I dived into the code and it seems like the culprit is Visual Studio itself. `OnSolutionOpened` is logged unconditionally, right? So it should always appear in the log? 

Well, now I jsut experienced that the plain solution I mentioned in the previous post doesn't work either. When I close Visual Studio the log will say `OnSolutionClosed` but not `OnSolutionOpened`! Seems like Visual Studio doesn't fire that event (if that's the right term for it) at all sometimes?

**Comment by mlangkabel** [comment] 2019-07-06 16:09
Wow, thanks for looking into it! If you need to do some changes to the code, we would be happy to accept a pull request!

So it looks like the solution is opened before the initialize method had a chance to register the event handlers. Did you open VS by opening your solution? Or did you open VS first and then inside VS chose the solution to be loaded?

**Comment by loic-joly-sonarsource** [comment] 2019-07-08 12:18
I tried to reproduce my issue, because the way you described it seemed different from mine... And different it is, but in strange ways...

If I enable logging inside of SourceTrail, then when loading some projects wile starting VS, the menu is grayed-out.

If logging is disabled, when doing the same stuff, I have my initial behaviour : After starting VS with a solution, the menu is enabled. But if I seect it, it becomes grayed-out until I restart visual studio.

On a project where I correctly run it before (by switching VS to english), it now works when I try to start it again, even with VS switched back to english.

I'm not going to be able to do many more tests, since I'm reaching the end of my evaluation period.

**Comment by egraether** [comment] 2019-07-08 12:30
Thanks for the update! @mlangkabel, the main developer of the plugin, is out of office the next two weeks. I just extended your test license.

**Comment by mlangkabel** [comment] 2019-08-19 09:05
Hi @loic-joly-sonarsource, do you by any change still have the logs written by the Sourcetrail VS Extension? If you had logging enabled, you should be able to find them at `C:\Users\You\AppData\Local\Coati Software\Plugins\VS`.
Can you please try to compare them with the logs I posted here on July 5th and tell us if they look differently?

**Comment by loic-joly-sonarsource** [comment] 2019-08-19 09:25
I'm attaching all the logs from that day here:
[coatilogs.zip](https://github.com/CoatiSoftware/vs-sourcetrail/files/3515060/coatilogs.zip)

When I look in the `C:\Users\ME\AppData\Local\Coati Software\Plugins\VS\cdbs.sourcetraildata` file, I also see things like:
```
    <lastUpdated>24/06/2019 15:51:45</lastUpdated>
```

Which looks like a french-formatted date. Maybe not using a culture-invariant local might be the cause of the issue?


I hope this helps,

**Comment by mlangkabel** [comment] 2019-08-19 12:26
Thank you for providing the logs! From what it seems like, I managed to reproduce your issue and we just published a new release on the VS marketplace.

**Closed by mlangkabel** 2019-08-19 12:26 UTC
