### ISSUE TITLE
Support Visual Studio Makefile Projects

### ISSUE THREAD

**Issue by fire** [CoatiSoftware/vs-sourcetrail#8] opened 2017-09-22 12:36 UTC
Hi there,

I also tried it on Godot game engine and both UE4 and Godot have their own custom non visual studio method of compiling.

Godot uses scons + nmake.

Unreal Engine uses UBT.

**Comment by fire** [comment] 2017-09-22 12:36
https://github.com/godotengine/godot

**Comment by mlangkabel** [comment] 2017-09-25 08:56
Thanks @fire for reporting this one. We have been able to reproduce your issue. It seems like Godot generates a Visual Studio "Makefile Project", which is currently not supported by the Sourcetrail Extension for Visual Studio. We will try to figure out a way to change that.

**Comment by mlangkabel** [comment] 2017-09-26 11:52
Fixed by adding an implementation for handling Visual Studio NMake projects in 381887b4c0e132195dcdef516ab039d12c6235d4.

However, it looks like the Visual Studio solution generated by Godot is not configured correctly. To be more precise: The Visual Studio solution is missing all the required preprocessor definitions. Furthermore all the include search directories are starting with a `#` character which is not a valid syntax in Visual Studio. 

This is why both, the Visual Studio intellisense and the Sourcetrail extension are not working correctly for this generated solution.

**Closed by mlangkabel** 2017-09-26 11:52 UTC
Labels: feature
